package view;

import controller.Controller;
import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import resources.Utilities;

/**
 * Clase con la GUI de la aplicación
 * @author Sonia Juanino Vega
 */
public class SeriesGUI extends javax.swing.JFrame {
    
    public String mp4 = null;
    public JFileChooser fileChooser;
    private DefaultTableModel jTableModelo;
    private DefaultListModel jListModelo;

    /**
     * Creates new form NewJFrame
     */
    public SeriesGUI() {
        initComponents();      
        fileChooser = new JFileChooser();
        cleanTxtFields();
        initJtable();
        initJList();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupEpisode = new javax.swing.ButtonGroup();
        btnGroupSeason = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        tabs = new javax.swing.JTabbedPane();
        panelEpisode = new javax.swing.JPanel();
        txtDirectory = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        scrollPaneList = new javax.swing.JScrollPane();
        jlFiles = new javax.swing.JList<>();
        btnExit = new javax.swing.JButton();
        pnlRadioButtons = new javax.swing.JPanel();
        lblProceso = new javax.swing.JLabel();
        panelSeason = new javax.swing.JPanel();
        scrollPaneTable = new javax.swing.JScrollPane();
        tblEpisodes = new javax.swing.JTable();
        pnlTempRadioBtns = new javax.swing.JPanel();
        txtDirEpisodes = new javax.swing.JTextField();
        btnSearchEps = new javax.swing.JButton();
        lblFinProcesoSubs = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SubtitlesRenamer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tabs.setMinimumSize(new java.awt.Dimension(800, 430));
        tabs.setPreferredSize(new java.awt.Dimension(800, 450));

        panelEpisode.setMinimumSize(new java.awt.Dimension(300, 400));
        panelEpisode.setPreferredSize(new java.awt.Dimension(620, 420));
        panelEpisode.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelEpisode.add(txtDirectory, gridBagConstraints);

        btnSearch.setText("...");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelEpisode.add(btnSearch, gridBagConstraints);

        scrollPaneList.setPreferredSize(new java.awt.Dimension(100, 100));

        jlFiles.setPreferredSize(new java.awt.Dimension(100, 0));
        scrollPaneList.setViewportView(jlFiles);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelEpisode.add(scrollPaneList, gridBagConstraints);

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelEpisode.add(btnExit, gridBagConstraints);

        pnlRadioButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlRadioButtons.setAutoscrolls(true);
        pnlRadioButtons.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelEpisode.add(pnlRadioButtons, gridBagConstraints);

        lblProceso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProceso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelEpisode.add(lblProceso, gridBagConstraints);

        tabs.addTab("Episodio Único", panelEpisode);

        panelSeason.setLayout(new java.awt.GridBagLayout());

        scrollPaneTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPaneTable.setPreferredSize(new java.awt.Dimension(100, 100));

        tblEpisodes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblEpisodes.setAutoscrolls(false);
        tblEpisodes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEpisodesMouseClicked(evt);
            }
        });
        scrollPaneTable.setViewportView(tblEpisodes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelSeason.add(scrollPaneTable, gridBagConstraints);

        pnlTempRadioBtns.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTempRadioBtns.setPreferredSize(new java.awt.Dimension(100, 100));
        pnlTempRadioBtns.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelSeason.add(pnlTempRadioBtns, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelSeason.add(txtDirEpisodes, gridBagConstraints);

        btnSearchEps.setText("...");
        btnSearchEps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEpsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelSeason.add(btnSearchEps, gridBagConstraints);

        lblFinProcesoSubs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFinProcesoSubs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinProcesoSubs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelSeason.add(lblFinProcesoSubs, gridBagConstraints);

        tabs.addTab("Temporada Completa", panelSeason);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(tabs, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //========================================================================//
    // Metodos para limpiar o preparar componentes                            //
    //========================================================================// 
    
    /** Limpia los JTextFields y las JLabels */
    private void cleanTxtFields() {
        lblProceso.setVisible(false);
        lblFinProcesoSubs.setVisible(false);
        txtDirEpisodes.setText(null);
        txtDirectory.setText(null);
    }
     
    /** Inicia la JList */
    private void initJList() {
        this.jListModelo = new DefaultListModel();
        this.jlFiles.setModel(jListModelo);
    }
            
    /** Inicia la JTable */
    private void initJtable() {
        jTableModelo = new DefaultTableModel();
        tblEpisodes.setModel(jTableModelo);
        tblEpisodes.setDefaultEditor(Object.class, null); // Hace que las celdas no sean editables  
        jTableModelo.addColumn("Episodios");
    }
    
    /** Elimina los elementos que estaban en la JTable */
    private void clearJTable() {
        DefaultTableModel model = (DefaultTableModel) this.tblEpisodes.getModel();
        model.setRowCount(0);
    }
    
    /** Elimina los elementos que estaban el JList */
    private void clearJList() {
        DefaultListModel listModel = (DefaultListModel) this.jlFiles.getModel();
        listModel.removeAllElements();
    }
        
    private void btnSearchEpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEpsActionPerformed
        cleanTxtFields();
        clearJTable();
        Utilities.removeRadioButtons(this.pnlTempRadioBtns);
        Controller.searchSeason();
    }//GEN-LAST:event_btnSearchEpsActionPerformed

    private void tblEpisodesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEpisodesMouseClicked
        Utilities.removeRadioButtons(this.pnlTempRadioBtns);
        this.lblFinProcesoSubs.setVisible(false);
        int row = tblEpisodes.rowAtPoint(evt.getPoint());
        int column = tblEpisodes.columnAtPoint(evt.getPoint());
        String dato = String.valueOf(this.tblEpisodes.getValueAt(row,column)); // se obtiene el valor de la celda
        Controller.episodeClicked(dato);
    }//GEN-LAST:event_tblEpisodesMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        this.cleanTxtFields();
        this.clearJList();
        Utilities.removeRadioButtons(this.pnlRadioButtons);
        Controller.searchEpisode();
    }//GEN-LAST:event_btnSearchActionPerformed

    //========================================================================//
    // Setters y Getters de los componentes                                   //
    //========================================================================// 
    
    public JList<String> getJlFiles() {
        return jlFiles;
    }

    public void setJlFiles(JList<String> jlFiles) {
        this.jlFiles = jlFiles;
    }

    public JPanel getPnlRadioButtons() {
        return pnlRadioButtons;
    }

    public void setPnlRadioButtons(JPanel pnlRadioButtons) {
        this.pnlRadioButtons = pnlRadioButtons;
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public void setFileChooser(JFileChooser fileChooser) {
        this.fileChooser = fileChooser;
    }

    public DefaultTableModel getjTableModelo() {
        return jTableModelo;
    }

    public void setjTableModelo(DefaultTableModel jTableModelo) {
        this.jTableModelo = jTableModelo;
    }

    public JButton getBtnSearch() {
        return btnSearch;
    }

    public void setBtnSearch(JButton btnSearch) {
        this.btnSearch = btnSearch;
    }

    public JButton getBtnSearchEps() {
        return btnSearchEps;
    }

    public void setBtnSearchEps(JButton btnSearchEps) {
        this.btnSearchEps = btnSearchEps;
    }

    public ButtonGroup getBtnGroupEpisode() {
        return btnGroupEpisode;
    }

    public void setBtnGroupEpisode(ButtonGroup btnGroupEpisode) {
        this.btnGroupEpisode = btnGroupEpisode;
    }

    public ButtonGroup getBtnGroupSeason() {
        return btnGroupSeason;
    }

    public void setBtnGroupSeason(ButtonGroup btnGroupSeason) {
        this.btnGroupSeason = btnGroupSeason;
    }

    public JTable getTblEpisodes() {
        return tblEpisodes;
    }

    public void setTblEpisodes(JTable tblEpisodes) {
        this.tblEpisodes = tblEpisodes;
    }

    public JTextField getTxtDirEpisodes() {
        return txtDirEpisodes;
    }

    public void setTxtDirEpisodes(JTextField txtDirEpisodes) {
        this.txtDirEpisodes = txtDirEpisodes;
    }

    public JTextField getTxtDirectory() {
        return txtDirectory;
    }

    public void setTxtDirectory(JTextField txtDirectory) {
        this.txtDirectory = txtDirectory;
    }

    public JLabel getLblProceso() {
        return lblProceso;
    }

    public void setLblProceso(JLabel lblProceso) {
        this.lblProceso = lblProceso;
    }

    public JPanel getPnlTempRadioBtns() {
        return pnlTempRadioBtns;
    }

    public void setPnlTempRadioBtns(JPanel pnlTempRadioBtns) {
        this.pnlTempRadioBtns = pnlTempRadioBtns;
    }

    public JLabel getLblFinProcesoSubs() {
        return lblFinProcesoSubs;
    }

    public void setLblFinProcesoSubs(JLabel lblFinProcesoSubs) {
        this.lblFinProcesoSubs = lblFinProcesoSubs;
    }

    public DefaultListModel getjListModelo() {
        return jListModelo;
    }

    public void setjListModelo(DefaultListModel jListModelo) {
        this.jListModelo = jListModelo;
    }
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupEpisode;
    private javax.swing.ButtonGroup btnGroupSeason;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchEps;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JList<String> jlFiles;
    private javax.swing.JLabel lblFinProcesoSubs;
    private javax.swing.JLabel lblProceso;
    private javax.swing.JPanel panelEpisode;
    private javax.swing.JPanel panelSeason;
    private javax.swing.JPanel pnlRadioButtons;
    private javax.swing.JPanel pnlTempRadioBtns;
    private javax.swing.JScrollPane scrollPaneList;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblEpisodes;
    private javax.swing.JTextField txtDirEpisodes;
    private javax.swing.JTextField txtDirectory;
    // End of variables declaration//GEN-END:variables
} // End class SeriesGUI
